In [1]:
import numpy as np
data=[[1,2],[4,5],[7,8]]
arr=np.array(data)
arr

array([[1, 2],
       [4, 5],
       [7, 8]])

In [3]:
arr.mean()

4.5

In [4]:
arr.sum()
arr.std()

27

In [1]:
my_arr=np.arange(10)
np.save('C:\Users\lenovo\PycharmProjects\dataAnalyse\simple',arr)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-1-ec627bf476c7>, line 2)

In [2]:
my_arr=np.arange(10)
np.save('C:\Users\lenovo\PycharmProjects\dataAnalyse\simple',my_arr)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-2-92b658c4991e>, line 2)

In [3]:
my_arr

NameError: name 'my_arr' is not defined

In [5]:
my_arr=np.arange(10)
np.save('C:\Users\lenovo\PycharmProjects\dataAnalyse\simple',my_arr)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-5-92b658c4991e>, line 2)

In [6]:
my_arr

NameError: name 'my_arr' is not defined

import numpy as np
my_arr=np.arange(10)
np.save('C:\Users\lenovo\PycharmProjects\dataAnalyse\simple',my_arr)

my_arr

In [9]:
my_arr=np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.save(r'C:\Users\lenovo\PycharmProjects\dataAnalyse\simple',my_arr)

In [11]:
np.save(r'C:\Users\lenovo\PycharmProjects\dataAnalyse\simple',my_arr)

In [12]:
np.load(r'C:\Users\lenovo\PycharmProjects\dataAnalyse\simple')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lenovo\\PycharmProjects\\dataAnalyse\\simple'

In [13]:
r'C:\Users\lenovo\PycharmProjects\dataAnalyse\simple.npy'

'C:\\Users\\lenovo\\PycharmProjects\\dataAnalyse\\simple.npy'

In [14]:
np.load(r'C:\Users\lenovo\PycharmProjects\dataAnalyse\simple.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
new_my_arr=np.arange(0,5)
np.savez(r'C:\Users\lenovo\PycharmProjects\dataAnalyse\simple1.npy',a=my_arr,b=new_my_arr)

In [16]:
aim=np.load(r'C:\Users\lenovo\PycharmProjects\dataAnalyse\simple1.npy.npz')
ain['a']

NameError: name 'ain' is not defined

In [17]:
aim=np.load(r'C:\Users\lenovo\PycharmProjects\dataAnalyse\simple1.npy.npz')
aim['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
aim['b']

array([0, 1, 2, 3, 4])

In [19]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a+b
c

array([[ 6,  8],
       [10, 12]])

In [20]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [21]:
c

array([[ 6,  8],
       [10, 12]])

In [22]:
c.trace

<function ndarray.trace>

In [23]:
c.trace()

18

In [24]:
c.det

AttributeError: 'numpy.ndarray' object has no attribute 'det'

In [25]:
c.det()

AttributeError: 'numpy.ndarray' object has no attribute 'det'

In [26]:
c.eig()

AttributeError: 'numpy.ndarray' object has no attribute 'eig'

In [27]:
c.inv()

AttributeError: 'numpy.ndarray' object has no attribute 'inv'

In [28]:
from numpy.linalg import inv,eig,det
print(c.inv())
print(c.eig())
print(c.det())

AttributeError: 'numpy.ndarray' object has no attribute 'inv'

In [29]:
c

array([[ 6,  8],
       [10, 12]])

In [30]:
from numpy.linalg import inv,eig,det
print(c.inv)
print(c.eig)
print(c.det)

AttributeError: 'numpy.ndarray' object has no attribute 'inv'

In [2]:
import pandas as pd
obj=pd.Series([1,2,3,4]
obj

SyntaxError: invalid syntax (<ipython-input-2-0422c2e3cd83>, line 3)

In [32]:
obj=pd.Series([1,2,3,4])
obj

NameError: name 'pd' is not defined

In [33]:
import pandas as pd
obj=pd.Series([1,2,3,4])
obj

0    1
1    2
2    3
3    4
dtype: int64

In [34]:
print(obj.value)
print(obj.index)

AttributeError: 'Series' object has no attribute 'value'

In [35]:
print(obj.values)
print(obj.index)

[1 2 3 4]
RangeIndex(start=0, stop=4, step=1)


In [36]:
obj2=pd.Series([1,2,3,4],index=['zhao','qian','sun','li'])
obj2

zhao    1
qian    2
sun     3
li      4
dtype: int64

In [37]:
obj2['li']


4

In [38]:
obj2['li']>obj2['zhao']

True

In [1]:
data

NameError: name 'data' is not defined

In [40]:
del data
data={'shu':1,'niu':2,'hu':3,'tu':4,'long':5,'she':6}
obj3=pd.Series(data)
obj3

shu     1
niu     2
hu      3
tu      4
long    5
she     6
dtype: int64

In [41]:
states #在尝试states该变量是否存在

NameError: name 'states' is not defined

In [2]:
states=['one','two','three','four','five','six']
obj3=pd.Series(data,index=states)
obj3

NameError: name 'pd' is not defined